[build]
    ignore = "if [ ${COMMIT_REF} == ${CACHED_COMMIT_REF} ] ; then false ; else git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../devconnect-app ../lib ; fi"
    command = "yarn build"
    publish = ".next"

[build.environment]
  DEPLOY_ID = "${DEPLOY_ID}"

[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"
  [functions.environment]
    DEPLOY_ID = "${DEPLOY_ID}"

[[plugins]]
    package = "@netlify/plugin-nextjs"
