[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"

[build]
    ignore = "if [ ${COMMIT_REF} == ${CACHED_COMMIT_REF} ] ; then false ; else git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../devconnect-app ../lib ; fi"
    command = "chmod +x ./build.sh && ./build.sh && pnpm run build"
    publish = ".next"

[[plugins]]
    package = "@netlify/plugin-nextjs"

[build.environment]
PNPM_FLAGS = "--filter devconnect-app..."
NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
  from = "https://devconnect-pwa.netlify.app/*"
  to = "https://app.devconnect.org/:splat"
  status = 301
  force = true
