[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"

[build]
    ignore = "if [ ${COMMIT_REF} == ${CACHED_COMMIT_REF} ] ; then false ; else git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../devconnect-app ../lib ; fi"
    command = "chmod +x ./build.sh && ./build.sh && pnpm run build"
    publish = ".next"

[[plugins]]
    package = "@netlify/plugin-nextjs"
