export enum Role {
    Developer = 'Developer',
    Designer = 'Designer',
    Researcher = 'Researcher',
    Entrepreneur = 'Entrepreneur',
    Marketing = 'Marketing',
    Product = 'Product',
    Investor = 'Investor',
    Operations = 'Operations',
    Sales = 'Sales',
    Community = 'Community',
    Legal = 'Legal',
    People = 'People',
}
  
export enum Track {
    CoreProtocol = 'Core Protocol',
    Cypherpunk = 'Cypherpunk & Privacy',
    Usability = 'Usability',
    RealWorldEthereum = 'Real World Ethereum',
    AppliedCryptography = 'Applied Cryptography',
    Cryptoeconomics = 'Cryptoeconomics',
    Coordination = 'Coordination',
    DeveloperExperience = 'Developer Experience',
    Security = 'Security',
    Layer2s = 'Layer2s',
}

export enum Tag {
    Layer1 = 'Layer1',
    Staking = 'Staking',
    EIP = 'EIP',
    SSF = 'SSF',
    Consensus = 'Consensus',
    FOSS = 'FOSS',
    CensorshipResistance = 'Censorship Resistance',
    Privacy = 'Privacy',
    Identity = 'Identity',
    Decentralization = 'Decentralization',
    UI = 'UI',
    UX = 'UX',
    Design = 'Design',
    AccountAbstraction = 'Account Abstraction',
    DesignThinking = 'Design Thinking',
    UserResearch = 'User Research',
    UseCases = 'Use Cases',
    Impact = 'Impact',
    ProductMarketFit = 'Product-Market Fit',
    Regulatory = 'Regulatory',
    ZKP = 'ZKP',
    MPC = 'MPC',
    Mixers = 'Mixers',
    Signatures = 'Signatures',
    QuantumResistance = 'Quantum Resistance',
    MechanismDesign = 'Mechanism Design',
    GameTheory = 'Game Theory',
    Tokenomics = 'Tokenomics',
    MEV = 'MEV',
    Intents = 'Intents',
    Restaking = 'Restaking',
    DAOs = 'DAOs',
    Governance = 'Governance',
    QuadraticVoting = 'Quadratic Voting',
    Cooperation = 'Cooperation',
    DevEx = 'DevEx',
    Libraries = 'Libraries',
    Tooling = 'Tooling',
    DevRel = 'DevRel',
    Infrastructure = 'Infrastructure',
    Auditing = 'Auditing',
    Bugs = 'Bugs',
    Hacks = 'Hacks',
    KeyManagement = 'Key Management',
    Scalability = 'Scalability',
    Layer2 = 'Layer 2',
    Rollups = 'Rollups',
    DAS = 'DAS',
    Bridges = 'Bridges',
    ZK_EVM = 'zkEVM',
}
