[build]
    ignore = "if [ ${COMMIT_REF} == ${CACHED_COMMIT_REF} ] ; then false ; else git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../devcon ../lib ; fi"
    command = "pnpm run build"
    publish = ".next"

[functions]
  included_files = ["src/content/**/*"]

[[plugins]]
    package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/grants"
  to = "https://esp.ethereum.foundation/devcon-grants"
  status = 302
  force = true

[[redirects]]
  from = "/speak"
  to = "https://speak.devcon.org/devcon7-sea/cfp"
  status = 302
  force = true

[[redirects]]
  from = "/side-events"
  to = "https://devcon.org/devcon-week"
  status = 302
  force = true

[[redirects]]
  from = "/schedule"
  to = "https://app.devcon.org/schedule"
  status = 302
  force = true
