import { NextRequest, NextResponse } from 'next/server';
import poapMints from '@/data/poap-mints.json';

/**
 * API endpoint to verify POAP ownership
 * POST /api/poap
 * Body: { addresses: string[], dropId: string }
 *
 * Ownership used to be checked live against the POAP Compass GraphQL API
 * (public.compass.poap.tech), which died with the POAP project shutdown.
 * It is now checked against the final mints snapshot in
 * src/data/poap-mints.json ({ dropId: { address: minted_on } }), generated by
 * scripts/build-poap-static-data.ts from discounts/inputs/devconnect-arg/.
 * Minting ended with the event, so the snapshot is complete and final.
 */
export async function POST(request: NextRequest) {
  try {
    const { addresses, dropId } = await request.json();

    if (!addresses || !Array.isArray(addresses) || addresses.length === 0) {
      return NextResponse.json(
        { error: 'Invalid or missing addresses' },
        { status: 400 }
      );
    }

    if (!dropId || typeof dropId !== 'string') {
      return NextResponse.json(
        { error: 'Invalid or missing dropId' },
        { status: 400 }
      );
    }

    const result = checkPoapOwnership(addresses, dropId);

    return NextResponse.json(result);
  } catch (error) {
    console.error('POAP verification API error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

/**
 * Check if user owns the specified POAP
 * @param addresses - Array of user addresses to check
 * @param dropId - POAP drop ID to verify
 * @returns {hasPoap: boolean, mintedOn?: number} - Ownership status and mint date (Unix timestamp)
 */
function checkPoapOwnership(addresses: string[], dropId: string): { hasPoap: boolean; mintedOn?: number } {
  const holders: Record<string, number> | undefined = (poapMints as Record<string, Record<string, number>>)[dropId];

  if (!holders) {
    console.warn(`POAP check: drop ${dropId} not in the mints snapshot`);
    return { hasPoap: false };
  }

  const mintDates = addresses
    .map(address => holders[address.toLowerCase()])
    .filter((mintedOn): mintedOn is number => mintedOn !== undefined);

  const hasPoap = mintDates.length > 0;
  const mintedOn = hasPoap ? Math.min(...mintDates) : undefined;

  console.log(`POAP check result: ${hasPoap ? 'Found' : 'Not found'} POAP ${dropId} for addresses:`, addresses);

  return { hasPoap, mintedOn };
}
