/* eslint-disable */
// AUTO-GENERATED by `pnpm speakers:pull` (src/scripts/pull-constellation-speakers.ts).
// Do not edit by hand — curation lives in speakers-allowlist.ts. Re-run the script after changing it.
import type { StaticImageData } from 'next/image'

import img3JEDML from './assets/portraits/dorde-mijovic.webp'
import img3QYPGS from './assets/portraits/preston-vander-vos.webp'
import img7BLNXR from './assets/portraits/griff-green.webp'
import img8FL8QW from './assets/portraits/zachary-williamson.webp'
import imgB9V8HC from './assets/portraits/victoria-kozlova.webp'
import imgDURU3V from './assets/portraits/santiagodevrel.webp'
import imgFZ8PA3 from './assets/portraits/hart-montgomery.webp'
import imgG9LYGU from './assets/portraits/justin-drake.webp'
import imgGVKNCK from './assets/portraits/meinhard-benn.webp'
import imgJ7URYL from './assets/portraits/janmajaya-mall.webp'
import imgLP7S9M from './assets/portraits/kati-illes.webp'
import imgMPDBM3 from './assets/portraits/johanna-moran.webp'
import imgMWSEWZ from './assets/portraits/sandeep-nailwal.webp'
import imgRMPP9E from './assets/portraits/barnabe-monnot.webp'
import imgT8KAJP from './assets/portraits/jan-kalivoda.webp'
import imgTKDN87 from './assets/portraits/jason-chaskin.webp'
import imgW8UUCW from './assets/portraits/roger-dingledine.webp'
import imgZDA7LS from './assets/portraits/fatemeh-fannizadeh.webp'

export interface PulledSpeaker {
  id: string
  name: string
  /** Pretalx question 153 answer (or the manual entry’s company). Empty string when unanswered. */
  organization: string
  /** Bare X handle parsed from Pretalx question 142. */
  xHandle?: string
  image: StaticImageData
  source: 'pretalx' | 'manual'
}

export const PULLED_SPEAKERS: Record<string, PulledSpeaker> = {
  '3JEDML': {
    id: '3JEDML',
    name: 'Dorde Mijovic',
    organization: 'Monad Foundation',
    xHandle: 'mijovic988',
    image: img3JEDML,
    source: 'pretalx',
  },
  '3QYPGS': {
    id: '3QYPGS',
    name: 'Preston Vander Vos',
    organization: 'Circle',
    xHandle: 'PrestonVanderV',
    image: img3QYPGS,
    source: 'pretalx',
  },
  '7BLNXR': {
    id: '7BLNXR',
    name: 'Griff Green',
    organization: 'TheDAO Security Fund & Giveth',
    xHandle: 'griffgreen',
    image: img7BLNXR,
    source: 'pretalx',
  },
  '8FL8QW': {
    id: '8FL8QW',
    name: 'Zachary Williamson',
    organization: 'Aztec Foundation',
    xHandle: 'Zac_Aztec',
    image: img8FL8QW,
    source: 'pretalx',
  },
  B9V8HC: {
    id: 'B9V8HC',
    name: 'victoria kozlova',
    organization:
      'I am a PhD researcher studying society and technology with almost 5 years of experience working with blockchains, primarily in the Ethereum ecosystem. my current affiliation is with Tallinn University of Technology, Royal Melbourne Institute of Technology and DREAM+PLAN, EU-funded PhD program.',
    xHandle: 'vicosvv',
    image: imgB9V8HC,
    source: 'pretalx',
  },
  DURU3V: {
    id: 'DURU3V',
    name: 'SantiagoDevRel',
    organization: 'Golem Network',
    xHandle: 'santiagodevrel',
    image: imgDURU3V,
    source: 'pretalx',
  },
  FZ8PA3: {
    id: 'FZ8PA3',
    name: 'Hart Montgomery',
    organization:
      'Linux Foundation, and many of the foundations and projects in it (including LF Decentralized Trust, which hosts Besu, Lineth, Paladin, and more)',
    image: imgFZ8PA3,
    source: 'pretalx',
  },
  G9LYGU: {
    id: 'G9LYGU',
    name: 'Justin Drake',
    organization: 'Ethereum Foundation',
    image: imgG9LYGU,
    source: 'pretalx',
  },
  GVKNCK: { id: 'GVKNCK', name: 'Meinhard Benn', organization: 'Freedom Browser', image: imgGVKNCK, source: 'pretalx' },
  J7URYL: {
    id: 'J7URYL',
    name: 'Janmajaya Mall',
    organization: 'phantom.zone',
    xHandle: 'Janmajaya_mall',
    image: imgJ7URYL,
    source: 'pretalx',
  },
  LP7S9M: {
    id: 'LP7S9M',
    name: 'Kati Illes',
    organization: 'UNICEF, Office of Innovation, Cryptofund',
    image: imgLP7S9M,
    source: 'pretalx',
  },
  MPDBM3: { id: 'MPDBM3', name: 'Johanna Moran', organization: 'libp2p', image: imgMPDBM3, source: 'pretalx' },
  MWSEWZ: {
    id: 'MWSEWZ',
    name: 'Sandeep Nailwal',
    organization: 'Polygon Labs',
    xHandle: 'sandeepnailwal',
    image: imgMWSEWZ,
    source: 'pretalx',
  },
  RMPP9E: {
    id: 'RMPP9E',
    name: 'Barnabé Monnot',
    organization: 'Ethlabs',
    xHandle: 'barnabemonnot',
    image: imgRMPP9E,
    source: 'pretalx',
  },
  T8KAJP: {
    id: 'T8KAJP',
    name: 'Jan Kalivoda',
    organization: 'ack3',
    xHandle: 'jaczkal',
    image: imgT8KAJP,
    source: 'pretalx',
  },
  TKDN87: {
    id: 'TKDN87',
    name: 'Jason Chaskin',
    organization: 'Ethereum Foundation',
    xHandle: 'jchaskin22',
    image: imgTKDN87,
    source: 'pretalx',
  },
  W8UUCW: {
    id: 'W8UUCW',
    name: 'Roger Dingledine',
    organization: 'The Tor Project',
    image: imgW8UUCW,
    source: 'pretalx',
  },
  ZDA7LS: {
    id: 'ZDA7LS',
    name: 'Fatemeh Fannizadeh',
    organization: 'EF Silviculture Society - Collective for Universal Basic Broadband Access',
    image: imgZDA7LS,
    source: 'pretalx',
  },
}
