import { defineConfig } from 'tinacms'
import faq from './templates/faq'
import past_events from './templates/past_events'
import dips from './templates/dips'
import index from './templates/index'
import programming from './templates/programming'
import { filenameToUrl } from '../../lib/cms/filenameToUrl'
// Your hosting provider likely exposes this as an environment variable
const branch = process.env.GITHUB_BRANCH || process.env.VERCEL_GIT_COMMIT_REF || process.env.HEAD || 'main'

console.log('TINA branch', branch)

const pageTemplates = [index, dips, past_events, faq, programming]

export default defineConfig({
  branch,
  // Get this from tina.io
  clientId: process.env.TINA_CLIENT_ID,
  // Get this from tina.io
  token: process.env.TINA_TOKEN,
  build: {
    outputFolder: 'admin/tina',
    publicFolder: 'public',
  },
  media: {
    tina: {
      mediaRoot: 'cms-assets',
      publicFolder: 'public',
    },
  },
  // See docs on content modeling for more info on how to setup new content models: https://tina.io/docs/schema/
  schema: {
    collections: [
      {
        name: 'pages',
        label: 'Pages',
        path: 'content/en/pages',
        format: 'mdx',
        templates: pageTemplates,
        ui: {
          router: ({ document }) => {
            // If no explicit filenameToUrl mapping, replace underscores with dashes - won't catch everything, but probably good enough
            if (!filenameToUrl[document._sys.filename]) {
              return document._sys.filename.replace(/_/g, '-')
            }

            return filenameToUrl[document._sys.filename] || document._sys.filename
          },
        },
      },
      {
        name: 'pagesHi',
        label: 'Pages (Hindi)',
        path: 'content/hi/pages',
        format: 'mdx',
        templates: pageTemplates,
        ui: {
          // Machine-generated by the translation pipeline — not meant to be hand-edited
          // via Tina UI. Hide create/delete but keep discoverable for read queries.
          allowedActions: {
            create: false,
            delete: false,
          },
          router: ({ document }) => {
            if (!filenameToUrl[document._sys.filename]) {
              return `/hi${document._sys.filename.replace(/_/g, '-')}`
            }
            const base = filenameToUrl[document._sys.filename] || document._sys.filename
            return `/hi${base === '/' ? '' : base}`
          },
        },
      },
    ],
  },
})
