-- Create table for storing cursors
CREATE TABLE IF NOT EXISTS "at-proto-cursors" (
    "id" integer PRIMARY KEY,
    "cursor" text,
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now()
);

-- Create table for storing events
CREATE TABLE IF NOT EXISTS "atproto-events" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uri" text NOT NULL,
    "cid" text NOT NULL,
    "author" text NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    "data" jsonb NOT NULL,
    "lexicon" text NOT NULL,
    "did" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now()
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS "atproto-events_uri_idx" ON "atproto-events" ("uri");
CREATE INDEX IF NOT EXISTS "atproto-events_author_idx" ON "atproto-events" ("author");
CREATE INDEX IF NOT EXISTS "atproto-events_lexicon_idx" ON "atproto-events" ("lexicon");
CREATE INDEX IF NOT EXISTS "atproto-events_timestamp_idx" ON "atproto-events" ("timestamp"); 