-- Intended payer: bind payment to wallet so verify only accepts that payer
ALTER TABLE x402_pending_orders
  ADD COLUMN IF NOT EXISTS intended_payer TEXT;

COMMENT ON COLUMN x402_pending_orders.intended_payer IS 'Wallet address that must submit the payment (prevents tx reuse attack)';

-- Rate limit: log verify attempts for per-ref and per-IP limits
CREATE TABLE IF NOT EXISTS x402_verify_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_x402_verify_attempts_key_created ON x402_verify_attempts(key, created_at DESC);

ALTER TABLE x402_verify_attempts ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE x402_verify_attempts IS 'Rate limiting for /api/x402/tickets/verify; key = verify_ref:paymentRef or verify_ip:clientIp';
