-- devcon8_discount_codes: pool of secret codes distributed via URL
-- Race-condition safety: app layer uses atomic UPDATE ... WHERE claimed_by IS NULL
-- so only one concurrent request can claim a given code.
CREATE TABLE devcon8_discount_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,                  -- UNIQUE implicitly creates an index
    claimed_by TEXT,                            -- userId/nullifier from verification
    claimed_at TIMESTAMP WITH TIME ZONE,
    voucher_code TEXT,                          -- assigned voucher code after redemption
    collection TEXT NOT NULL DEFAULT 'default',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- No explicit index on code — the UNIQUE constraint already provides one
CREATE INDEX idx_devcon8_discount_codes_collection ON devcon8_discount_codes(collection);
CREATE INDEX idx_devcon8_discount_codes_unclaimed ON devcon8_discount_codes(collection) WHERE claimed_by IS NULL;

-- devcon8_discount_vouchers: pool of Pretix voucher codes for assignment
-- Race-condition safety: app layer uses atomic UPDATE ... WHERE assigned_to IS NULL
-- so only one concurrent request can be assigned a given voucher.
CREATE TABLE devcon8_discount_vouchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,                  -- UNIQUE implicitly creates an index
    pretix_voucher_id INTEGER NOT NULL,         -- always populated from Pretix API
    item_id INTEGER NOT NULL,                   -- always populated from Pretix API
    tag TEXT NOT NULL DEFAULT 'default',
    assigned_to TEXT,                           -- userId that consumed this voucher
    assigned_at TIMESTAMP WITH TIME ZONE,
    collection TEXT NOT NULL DEFAULT 'default',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- No explicit index on code — the UNIQUE constraint already provides one
-- Partial index matches app query: WHERE collection = ? AND assigned_to IS NULL
CREATE INDEX idx_devcon8_discount_vouchers_unassigned
    ON devcon8_discount_vouchers(collection) WHERE assigned_to IS NULL;

-- Foreign key: discount_codes.voucher_code → discount_vouchers.code
ALTER TABLE devcon8_discount_codes
    ADD CONSTRAINT fk_devcon8_discount_codes_voucher
    FOREIGN KEY (voucher_code) REFERENCES devcon8_discount_vouchers(code);

-- RLS enabled, no policies — access is intentionally service-role-only.
-- All app queries use SUPABASE_SERVICE_ROLE_KEY which bypasses RLS.
ALTER TABLE devcon8_discount_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE devcon8_discount_vouchers ENABLE ROW LEVEL SECURITY;
