-- Student discount voucher pool
-- Each row is a voucher code (bulk-imported from CSV).
-- Assignment: update email + assigned_at. Query by email for return visits.
-- Race-condition safety: app uses UPDATE ... WHERE email IS NULL
CREATE TABLE devcon8_student_vouchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    email TEXT UNIQUE,
    assigned_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Fast lookup for unassigned vouchers
CREATE INDEX idx_devcon8_student_vouchers_unassigned
    ON devcon8_student_vouchers(id) WHERE email IS NULL;

-- RLS enabled, service-role-only access
ALTER TABLE devcon8_student_vouchers ENABLE ROW LEVEL SECURITY;

-- Student discount application submissions
CREATE TABLE devcon8_student_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    university TEXT NOT NULL,
    year_of_study TEXT NOT NULL,
    field_of_study TEXT NOT NULL,
    country TEXT NOT NULL,
    essay_proof_of_work TEXT NOT NULL,
    classification_type TEXT,
    classification_domain TEXT,
    is_university_email BOOLEAN DEFAULT FALSE,
    signals TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE devcon8_student_applications ENABLE ROW LEVEL SECURITY;
